import { ASSET } from './AssetQuery';
import { ASSETS } from './AssetsQuery';
import { SELECTED_ASSET_SOURCE_ID, SET_SELECTED_ASSET_SOURCE_ID } from './SelectedAssetSourceQuery';
import ASSET_COLLECTIONS from './AssetCollectionQuery';
import ASSET_COUNT from './AssetCountQuery';
import ASSET_SOURCES from './AssetSourcesQuery';
import TAGS from './TagsQuery';
import {
    ASSET_COLLECTION_FRAGMENT,
    ASSET_FRAGMENT,
    ASSET_SOURCE_FRAGMENT,
    FILE_FRAGMENT,
    IPTC_PROPERTY_FRAGMENT,
    TAG_FRAGMENT
} from './Fragments';
import {
    CREATE_TAG,
    DELETE_ASSET,
    CREATE_ASSET_COLLECTION,
    DELETE_ASSET_COLLECTION,
    DELETE_TAG,
    IMPORT_ASSET,
    SET_ASSET_COLLECTIONS,
    SET_ASSET_TAGS,
    TAG_ASSET,
    UNTAG_ASSET,
    UPDATE_ASSET,
    UPDATE_ASSET_COLLECTION,
    UPDATE_TAG,
    UPLOAD_FILE,
    UPLOAD_FILES
} from './Mutations';
import { SET_VIEW_MODE_SELECTION, VIEW_MODE_SELECTION } from './ViewModeSelectionQuery';
import { CONFIG } from './ConfigQuery';

export {
    ASSET,
    ASSETS,
    ASSET_COLLECTIONS,
    ASSET_COLLECTION_FRAGMENT,
    ASSET_COUNT,
    ASSET_FRAGMENT,
    ASSET_SOURCES,
    ASSET_SOURCE_FRAGMENT,
    CONFIG,
    CREATE_ASSET_COLLECTION,
    DELETE_ASSET_COLLECTION,
    CREATE_TAG,
    DELETE_ASSET,
    DELETE_TAG,
    FILE_FRAGMENT,
    IMPORT_ASSET,
    IPTC_PROPERTY_FRAGMENT,
    SELECTED_ASSET_SOURCE_ID,
    SET_ASSET_COLLECTIONS,
    SET_ASSET_TAGS,
    SET_SELECTED_ASSET_SOURCE_ID,
    SET_VIEW_MODE_SELECTION,
    TAGS,
    TAG_ASSET,
    TAG_FRAGMENT,
    UNTAG_ASSET,
    UPDATE_ASSET,
    UPDATE_ASSET_COLLECTION,
    UPDATE_TAG,
    UPLOAD_FILE,
    UPLOAD_FILES,
    VIEW_MODE_SELECTION
};
