approvedGitRepositories:
  - "**"

compressionLevel: mixed

enableGlobalCache: true

enableScripts: true

catalog:
  "@apollo/client": ^3.3.13
  apollo-upload-client: ^14.1.3
  react: ^17.0.2
  react-redux: ^5.1.2
  recoil: ^0.7.7
  tsx: ^4.23.12

nodeLinker: node-modules

npmMinimalAgeGate: 0

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.18.0.cjs
