<?php

declare(strict_types=1);

namespace Flowpack\Media\Ui\Controller;

/*
 * This file is part of the Flowpack.Media.Ui package.
 *
 * (c) Contributors of the Neos Project - www.neos.io
 *
 * This package is Open Source Software. For the full copyright and license
 * information, please view the LICENSE file which was distributed with this
 * source code.
 */

use Flowpack\Media\Ui\Exception;
use Flowpack\Media\Ui\GraphQL\Context\AssetSourceContext;
use Flowpack\Media\Ui\GraphQL\Types\AssetId;
use Flowpack\Media\Ui\GraphQL\Types\AssetIdentity;
use Flowpack\Media\Ui\GraphQL\Types\AssetSourceId;
use Neos\Flow\Annotations as Flow;
use Neos\Flow\I18n\Translator;
use Neos\Flow\Mvc\Exception\StopActionException;
use Neos\Fusion\View\FusionView;
use Neos\Media\Domain\Model\AssetInterface;
use Neos\Media\Domain\Service\AssetService;
use Neos\MetaData\ConfigurationProvider\ArrayMetaDataConfigurationProvider;
use Neos\MetaData\Domain\Dto\MetaDataConfiguration;
use Neos\MetaData\Domain\Dto\MetaDataPropertyName;
use Neos\MetaData\Domain\Dto\MetaDataPropertyValue;
use Neos\MetaData\Domain\Dto\MetaDataPropertyValues;
use Neos\MetaData\MetaDataManager;
use Neos\Neos\Controller\Module\AbstractModuleController;

#[Flow\Scope('singleton')]
class MediaController extends AbstractModuleController
{
    #[Flow\Inject]
    protected AssetSourceContext $assetSourceContext;

    #[Flow\Inject]
    protected AssetService $assetService;

    #[Flow\Inject]
    protected Translator $translator;

    /**
     * @var FusionView
     */
    protected $view;

    /**
     * @inheritdoc
     */
    protected $defaultViewObjectName = FusionView::class;

    /**
     * @inheritdoc
     */
    protected $viewFormatToObjectNameMap = [
        'html' => FusionView::class,
    ];

    protected ?MetaDataManager $metaDataManager;
    protected ?ArrayMetaDataConfigurationProvider $metaDataConfigurationProvider;

    public function initializeAction()
    {
        $this->metaDataManager = $this->objectManager->get(MetaDataManager::class);
        $this->metaDataConfigurationProvider = $this->objectManager->get(ArrayMetaDataConfigurationProvider::class);
        parent::initializeAction(); // TODO: Change the autogenerated stub
    }

    /**
     * Renders the media ui application
     */
    public function indexAction(): void
    {
    }

    public function editMetadataAction(
        AssetId $assetId,
        AssetSourceId $assetSourceId,
        ?string $metaDataDimensionSpacePointHash = null,
    ): void {
        $metaDataConfiguration = $this->metaDataConfigurationProvider?->getConfiguration();
        $dsps = $metaDataConfiguration?->dimensions;

        $dimensionSpacePoint = $metaDataDimensionSpacePointHash ? $metaDataConfiguration->dimensions->getByHash(
            $metaDataDimensionSpacePointHash
        ) : $dsps->getIterator()->current();
        $propertyValues = $this->metaDataManager?->getMetaDataPropertyValues(
            $assetId->value,
            $dimensionSpacePoint
        ) ?: MetaDataPropertyValues::createEmpty();
        $propertyDefinitions = $this->mapPropertyDefinitions($metaDataConfiguration, $propertyValues);

        $assetIdentity = AssetIdentity::create($assetId, $assetSourceId);
        $asset = $this->assetSourceContext->getAsset($assetIdentity->assetId, $assetIdentity->assetSourceId);

        $this->view->assignMultiple([
            'formSchema' => $propertyDefinitions,
            'asset' => $asset,
            'assetIdentity' => $assetIdentity,
            'assetDsps' => $dsps,
            'currentAssetDsp' => $metaDataDimensionSpacePointHash ?: $dimensionSpacePoint->hash,
        ]);
    }

    /**
     * @return array {type: string, editor: string|null, label: string, value: string|null}[]
     */
    protected function mapPropertyDefinitions(
        ?MetaDataConfiguration $metaDataConfiguration,
        MetaDataPropertyValues $propertyValues
    ): array {
        if (!isset($metaDataConfiguration) || iterator_count(
                $metaDataConfiguration->propertyDefinitions->getIterator()
            ) === 0) {
            return [];
        }

        $config = [];
        foreach ($metaDataConfiguration->propertyDefinitions as $propertyDefinition) {
            $propertyName = $propertyDefinition->name->value;
            $config[$propertyName] = [
                'type' => $propertyDefinition->type->name,
                'editor' => $propertyDefinition->ui->editorDefinition->editorType === 'Neos.Neos/Inspector/Editors/TextAreaEditor' ? 'textarea' : null,
                'label' => $this->translateByShortHandString($propertyDefinition->ui->label),
            ];
            foreach ($propertyValues as $propertyValueName => $propertyValue) {
                if ($propertyValueName === $propertyName) {
                    $config[$propertyName]['value'] = $propertyValue?->value;
                }
            }
        }
        return $config;
    }

    protected function translateByShortHandString(string $shortHand): string|null
    {
        $shortHandStringParts = explode(':', $shortHand);
        if (count($shortHandStringParts) === 3) {
            [$package, $source, $id] = $shortHandStringParts;
            return $this->translator->translateById(
                $id,
                [],
                null,
                null,
                str_replace('.', '/', $source),
                $package
            );
        }
        return null;
    }

    /**
     * @param string[] $postData
     * @throws Exception
     * @throws StopActionException
     */
    public function updateMetadataAction(
        AssetInterface $asset,
        string $metaDataDimensionSpacePointHash,
        array $postData,
    ): void {
        $assetIdentity = AssetIdentity::create(
            AssetId::fromString($this->persistenceManager->getIdentifierByObject($asset)),
            new AssetSourceId($asset->getAssetSourceIdentifier())
        );
        $metaDataDimensionSpacePoint = $this->metaDataConfigurationProvider->getConfiguration()->dimensions->getByHash(
            $metaDataDimensionSpacePointHash
        );
        foreach ($postData as $propertyName => $propertyValue) {
            $this->metaDataManager?->setMetaDataPropertyValue(
                $assetIdentity->assetId->value,
                MetaDataPropertyName::fromString($propertyName),
                MetaDataPropertyValue::parse($propertyValue),
                $metaDataDimensionSpacePoint,
            );
        }
        $this->assetService->emitAssetUpdated($asset);
        $this->redirect('index');
    }
}
