- name: 'Media API'
  uriPattern: 'neos/graphql/<GraphQLSubroutes>'
  subRoutes:
    'GraphQLSubroutes':
      package: 't3n.GraphQL'
      variables:
        'endpoint': 'media-assets'

- name: 'IFrame Media Chooser'
  uriPattern: 'neos/media/asset-choice'
  defaults:
    '@package': 'Flowpack.Media.Ui'
    '@controller': 'IframeMediaChooser'
    '@action': 'index'
