Neos:
  Neos:
    Ui:
      frontendConfiguration:
        Flowpack.Media.Ui:
          useNewMediaSelection: true
          queryAssetUsage: false
          pollForChanges: true
          showSimilarAssets: false
