Neos:
  Neos:
    Ui:
      frontendConfiguration:
        Flowpack.Media.Ui:
          useNewMediaSelection: true
          queryAssetUsage: false
          pollForChanges: true
          showSimilarAssets: false
          showVariantsEditor: false
          createAssetRedirectsOption: true
          pagination:
            assetsPerPage: 20
            maximumLinks: 5
