Neos:
  Neos:
    modules:
      management:
        submodules:
          mediaui:
            controller: \Flowpack\Media\Ui\Controller\MediaController
            label: 'Flowpack.Media.Ui:Main:module.label'
            description: 'Flowpack.Media.Ui:Main:module.description'
            icon: 'fas fa-image'
            privilegeTarget: 'Flowpack.Media.Ui:ManageAssets'
            additionalResources:
              javaScripts:
                - 'resource://Flowpack.Media.Ui/Public/Assets/main.bundle.js'
              styleSheets:
                - 'resource://Flowpack.Media.Ui/Public/Assets/extra-neos-wrapper.css'

    userInterface:
      translation:
        autoInclude:
          Flowpack.Media.Ui:
            - 'Main'

      inspector:
        dataTypes:
          Neos\Media\Domain\Model\Asset:
            editor: Flowpack.Media.Ui/Inspector/Editors/AssetEditor

    Ui:
      resources:
        javascript:
          Flowpack.Media.Ui:AssetEditor:
            resource: resource://Flowpack.Media.Ui/Public/AssetEditor/Plugin.js
