Neos:
  Neos:
    modules:
      management:
        submodules:
          mediaui:
            controller: \Flowpack\Media\Ui\Controller\MediaController
            label: 'Flowpack.Media.Ui:Main:module.label'
            description: 'Flowpack.Media.Ui:Main:module.description'
            icon: 'fas fa-image'
            privilegeTarget: 'Flowpack.Media.Ui:ManageAssets'
#            additionalResources:
#              styleSheets:
#                - 'resource://Flowpack.Media.Ui/Public/Styles/Main.css'

    userInterface:
      translation:
        autoInclude:
          Flowpack.Media.Ui:
            - 'Main'

  Flow:
    mvc:
      routes:
        'Flowpack.Media.Ui':
          position: 'start'

t3n:
  GraphQL:
    endpoints:
      'media-assets':
        schemas:
          root:
            typeDefs: 'resource://Flowpack.Media.Ui/Private/GraphQL/schema.root.graphql'
            resolverPathPattern: 'Flowpack\Media\Ui\GraphQL\Resolver\Type\{Type}Resolver'
            resolvers:
              Query: 'Flowpack\Media\Ui\GraphQL\Resolver\QueryResolver'
