Neos:
  Flow:
    mvc:
      routes:
        'Flowpack.Media.Ui':
          position: 'start'

    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
#              'Flowpack.Media.Ui:GraphQLControllers':
#                pattern: 'ControllerObjectName'
#                patternOptions:
#                  controllerObjectNamePattern: 't3n\GraphQL\Controller\.*'
              'Flowpack.Media.Ui:Controllers':
                pattern: 'ControllerObjectName'
                patternOptions:
                  controllerObjectNamePattern: 'Flowpack\Media\Ui\Controller\.*'

    http:
      middlewares:
        'Flowpack.Media.Ui:GraphQL':
          position: 'before routing'
          middleware: 'Flowpack.Media.Ui:GraphQLMiddleware'
