Neos:
  Neos:
    Ui:
      frontendConfiguration:
        Flowpack.Media.Ui:
          # Allow the user to let the system create redirects when assets are replaced or renamed
          createAssetRedirectsOption: true
          # Only allow a single asset collection selection per asset to treat collection like folders
          limitToSingleAssetCollectionPerAsset: false
          # Set the number of assets and links to be displayed per page
          pagination:
            assetsPerPage: 20
            maximumLinks: 5
          # Background polling for changes by other users
          pollForChanges: true
          # Settings for the property editor
          propertyEditor:
            collapsed: false
          # Query the usage of each asset when loading them, note: this requires a more performant implementation of the asset usage than the Neos default provides
          queryAssetUsage: false
          # Show similar assets, note: this requires an additional package to be installed
          showSimilarAssets: false
          # Show variants and the editor to modify them
          showVariantsEditor: false
          # Use the new media selection UI in the content module
          useNewMediaSelection: true
          # Additional filter options
          mediaTypeFilterOptions:
            image:
              'image/svg+xml': 'SVG'
              'image/png': 'PNG'
              'image/jpeg': 'JPEG'
              'image/gif': 'GIF'
              'image/webp': 'WEBP'
            document:
              'application/pdf': 'PDF'
            audio:
              'audio/mpeg': 'MP3'
              'audio/ogg': 'OGG'
              'audio/wav': 'WAV'
              'audio/webm': 'WEBM'
            video:
              'video/mp4': 'MP4'
              'video/ogg': 'OGG'
              'video/webm': 'WEBM'
