name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: yarn

      - name: Run linting
        run: yarn lint

  codestyle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        -
      - name: Update Composer
        run: |
          sudo composer self-update
          composer --version

      # Directory permissions for .composer are wrong, so we remove the complete directory
      # https://github.com/actions/virtual-environments/issues/824
      - name: Delete .composer directory
        run: |
          sudo rm -rf ~/.composer

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: dependencies-composer-${{ hashFiles('composer.json') }}

      - name: Install distribution
        run: |
          composer install --no-interaction --no-progress

      - name: PHPStan
        uses: docker://oskarstark/phpstan-ga
        with:
          args: analyse

  e2e:
    env:
      # Solves error when parcel tries to count cpus via lscpu
      PARCEL_WORKERS: 1

    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Build main module
        run: yarn build:module

      - name: Build secondary editor for Neos UI
        run: yarn build:editor

      - name: Run TestCafe
        run: yarn test:github-actions
