name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn

      - name: Run linting
        run: yarn lint

  codestyle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v3
        with:
          php-version: 7.4

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache
          key: dependencies-composer-${{ hashFiles('composer.json') }}

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 7.4
          version: 2

      - name: PHPStan
        uses: php-actions/phpstan@v3
        with:
          php_version: 7.4
          command: analyse

  e2e:
    env:
      # Solves error when parcel tries to count cpus via lscpu
      PARCEL_WORKERS: 1

    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn

      - name: Build main module
        run: yarn build:module

      - name: Build secondary editor for Neos UI
        run: yarn build:editor

      - name: Run TestCafe
        run: yarn test:github-actions
